name: "\U0001F41E Bug report"
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: "TiotBenjy"
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us reproduce and fix the bug.

  - type: dropdown
    id: package-version
    attributes:
      label: Package version
      description: You can run `npm ls <pkg-name>` to check the package version
      options:
        - 1.0.1 (Default)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: auth-endpoint
    attributes:
      label: authorizationEndpoint used in the configuration
      description: The `authorizationEndpoint` used in the configuration in the `ally.ts` file
      options:
          - tenant
          - common
          - organizations
          - consumers
      default: 0
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you are want to ask a question instead, then use the [discussion forum](https://github.com/TiotBenjy/ally-entra/discussions).
      placeholder: Bug description
    validations:
      required: true
  - type: input
    id: reproduction-repo
    attributes:
      label: Reproduction repo
      description: Link to the Reproduction repo that we can use to reproduce the issue
      placeholder: Optional, but recommended
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output if any
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: Optional, but recommended
      render: shell
