name: "\U0002139 Feature request"
description: Suggest an idea for this project

title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: "TiotBenjy"

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us understand your feature request.
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is. If you are want to ask a question instead, then use the [discussion forum](https://github.com/TiotBenjy/ally-entra/discussions).
      placeholder: Feature description
    validations:
        required: true
  - type: input
    id: feature-repo
    attributes:
        label: Feature repo
        description: Link to the Feature repo that we can use to reproduce the issue
        placeholder: Optional, but recommended
    validations:
        required: false

  - type: dropdown
    id: feature-priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
      default: 0
    validations:
      required: true
  - type: dropdown
    id: feature-impact
    attributes:
      label: Impact
      description: How will this feature impact the project?
      options:
        - Low
        - Medium
        - High
      default: 0
    validations:
      required: true
  - type: dropdown
    id: feature-urgency
    attributes:
      label: Urgency
      description: How soon do you need this feature?
      options:
        - Low
        - Medium
        - High
      default: 0
    validations:
      required: true
  - type: dropdown
    id: feature-implementation
    attributes:
      label: Implementation
      description: How do you think this feature should be implemented?
      options:
        - New feature
        - Improvement
        - Bug fix
      default: 0
    validations:
      required: true
